version: '3'
services:
  emacs:
    build: .
    volumes:
      - /:/volumes  # 映射当前目录到容器的 /workspace 目录
      - ./emacs.d:/root/.emacs.d  # 映射当前目录到容器的 /workspace 目录
    command: tail -f /dev/null # 启动 Emacs 以守护进程模式运行
    tty: true  # 保持容器运行，即使没有交互式命令运行
